/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ClassificationResult = IDL.Record({
  'isSpam' : IDL.Bool,
  'confidence' : IDL.Nat,
  'classification' : IDL.Text,
});
export const Stats = IDL.Record({
  'totalAnalyzed' : IDL.Nat,
  'totalSpam' : IDL.Nat,
  'totalHam' : IDL.Nat,
});

export const idlService = IDL.Service({
  'classifyMessage' : IDL.Func([IDL.Text], [ClassificationResult], []),
  'getStats' : IDL.Func([], [Stats], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ClassificationResult = IDL.Record({
    'isSpam' : IDL.Bool,
    'confidence' : IDL.Nat,
    'classification' : IDL.Text,
  });
  const Stats = IDL.Record({
    'totalAnalyzed' : IDL.Nat,
    'totalSpam' : IDL.Nat,
    'totalHam' : IDL.Nat,
  });
  
  return IDL.Service({
    'classifyMessage' : IDL.Func([IDL.Text], [ClassificationResult], []),
    'getStats' : IDL.Func([], [Stats], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };